language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install coveralls
script:
  - python tests.py
  - coverage run --source=serenare tests.py
after_success: coveralls
notifications:
  irc:
    channels:
      - "chat.freenode.net#seren"
